CI: clobber for special latest release

diff --git a/.github/workflows/python-dependencies.yml b/.github/workflows/python-dependencies.yml
--- a/.github/workflows/python-dependencies.yml
+++ b/.github/workflows/python-dependencies.yml
@@ -78,7 +78,24 @@ jobs:
         name: dclimplode-py${{ matrix.python-version }}-${{ matrix.python-platform }}-${{ matrix.os }}-${{ matrix.platform }}
         path: |
           dist/dclimplode-*
-
+    - name: Ensure special latest release exists
+      shell: bash
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        # Set continue on error to true
+        set +e
+        if [[ "$(gh --repo sourcehold/sourcehold-maps release view latest 2>&1)" == "release not found" ]]; then
+          set -e
+          gh --repo sourcehold/sourcehold-maps release create latest --latest
+        fi
+    - name: Upload dclimplode wheel to special latest release
+      shell: bash
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        gh --repo sourcehold/sourcehold-maps release upload latest dist/dclimplode-* --clobber
+        
     - name: Ensure release exists
       if: github.ref_type == 'tag'
       shell: bash
@@ -98,21 +115,3 @@ jobs:
         GH_TOKEN: ${{ github.token }}
       run: |
         gh --repo sourcehold/sourcehold-maps release upload ${{ github.ref_name }} dist/dclimplode-*
-
-    - name: Ensure special latest release exists
-      shell: bash
-      env:
-        GH_TOKEN: ${{ github.token }}
-      run: |
-        # Set continue on error to true
-        set +e
-        if [[ "$(gh --repo sourcehold/sourcehold-maps release view latest 2>&1)" == "release not found" ]]; then
-          set -e
-          gh --repo sourcehold/sourcehold-maps release create latest --latest
-        fi
-    - name: Upload dclimplode wheel to special latest release
-      shell: bash
-      env:
-        GH_TOKEN: ${{ github.token }}
-      run: |
-        gh --repo sourcehold/sourcehold-maps release upload latest dist/dclimplode-*
