CI: fix bug

diff --git a/.github/workflows/python-dependencies.yml b/.github/workflows/python-dependencies.yml
--- a/.github/workflows/python-dependencies.yml
+++ b/.github/workflows/python-dependencies.yml
@@ -1,7 +1,7 @@
 # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
 # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
 
-name: Python package
+name: Python dependencies
 
 on:
   workflow_dispatch: {}
@@ -87,7 +87,7 @@ jobs:
       run: |
         # Set continue on error to true
         set +e
-        if [[ "$(gh --repo sourcehold/sourcehold-maps release view $RELEASE_TAG 2>&1)" == "release not found" ]]; then
+        if [[ "$(gh --repo sourcehold/sourcehold-maps release view ${{ github.ref_name }} 2>&1)" == "release not found" ]]; then
           set -e
           gh --repo sourcehold/sourcehold-maps release create ${{ github.ref_name }} --latest
         fi
@@ -98,3 +98,21 @@ jobs:
         GH_TOKEN: ${{ github.token }}
       run: |
         gh --repo sourcehold/sourcehold-maps release upload ${{ github.ref_name }} dist/dclimplode-*
+
+    - name: Ensure special latest release exists
+      shell: bash
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        # Set continue on error to true
+        set +e
+        if [[ "$(gh --repo sourcehold/sourcehold-maps release view latest 2>&1)" == "release not found" ]]; then
+          set -e
+          gh --repo sourcehold/sourcehold-maps release create latest --latest
+        fi
+    - name: Upload dclimplode wheel to special latest release
+      shell: bash
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        gh --repo sourcehold/sourcehold-maps release upload latest dist/dclimplode-*
diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -84,6 +84,23 @@ jobs:
         path: |
           dist/sourcehold*
 
+    - name: Ensure special latest release exists
+      shell: bash
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        # Set continue on error to true
+        set +e
+        if [[ "$(gh --repo sourcehold/sourcehold-maps release view latest 2>&1)" == "release not found" ]]; then
+          set -e
+          gh --repo sourcehold/sourcehold-maps release create latest --latest
+        fi
+    - name: Upload pyinstaller to special latest release
+      shell: bash
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        gh --repo sourcehold/sourcehold-maps release upload latest dist/sourcehold*.whl
     - name: Ensure release exists
       if: github.ref_type == 'tag'
       shell: bash
@@ -92,7 +109,7 @@ jobs:
       run: |
         # Set continue on error to true
         set +e
-        if [[ "$(gh --repo sourcehold/sourcehold-maps release view $RELEASE_TAG 2>&1)" == "release not found" ]]; then
+        if [[ "$(gh --repo sourcehold/sourcehold-maps release view ${{ github.ref_name }} 2>&1)" == "release not found" ]]; then
           set -e
           gh --repo sourcehold/sourcehold-maps release create ${{ github.ref_name }} --latest
         fi
